
import "../globals.css";
import { Inter } from "next/font/google";
import React from "react";
import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignUp } from "@clerk/nextjs";
import Provider from "../ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
    >
      <html lang='en'>
        <body className={`${inter.className}`}>
          <Provider>

            {children}
          </Provider>
        </body>

      </html>
    </ClerkProvider>

  )
}
